#!/usr/bin/env python3
"""Render docs/api.md from the published API contract.

The inventory is generated so it cannot drift from the code: every name
comes from `tools/api_contract.SUPPORTED_DOWNSTREAM_IMPORTS`, and every
signature and summary is read off the object itself.

    python tools/generate_api_docs.py            # write docs/api.md
    python tools/generate_api_docs.py --check    # fail if it is stale

`tests/test_public_api_contract.py` runs the check, so a signature change
that misses the doc fails the suite rather than only a release.
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.api_contract import SUPPORTED_DOWNSTREAM_IMPORTS  # noqa: E402

DOC_PATH = Path(__file__).resolve().parent.parent / "docs" / "api.md"

PREAMBLE = """<!--
Generated by tools/generate_api_docs.py. Do not edit by hand.
Names come from tools/api_contract.py; signatures and summaries are read
off the objects. Regenerate with `python tools/generate_api_docs.py`.
-->

# Supported API

Everything below may be imported by name from the module it is listed
under, and downstream code can rely on it. The modules are separate on
purpose: there is no root-level re-export, so an import says which layer it
came from.

A public name absent from this page is reachable but incidental. It exists
because Python has no other way to express it, and it may move without a
deprecation. If something you need is missing here, open an issue rather
than importing it anyway.

Signatures are rendered from the code, and `tests/test_public_api_contract.py`
fails if this page and the code disagree.
"""


def _summary(obj) -> str:
    """First sentence of the object's own docstring, on one line.

    `inspect.getdoc` falls back to the *type's* docstring for an instance,
    which turned every outcome constant into `str.__doc__`. Only classes,
    functions and modules are asked.
    """
    if not (inspect.isclass(obj) or inspect.isroutine(obj)
            or inspect.ismodule(obj)):
        return ""
    doc = inspect.getdoc(obj)
    if not doc:
        return ""
    # The first paragraph, whole. Cutting at the first "." instead turned
    # "exits (i.e. after close)" into "exits (i." and "RFC 7252 §4.2" into
    # "RFC 7252 §4.", so no sentence splitting happens here.
    first = doc.strip().split("\n\n")[0]
    first = " ".join(part.strip() for part in first.splitlines())
    if len(first) > 200:
        first = first[:197].rstrip() + "..."
    # Docstrings here are RST, where ``x`` is inline code. Markdown reads
    # that as a code span too, so this is house style rather than a fix:
    # single backticks match the rest of the page.
    first = first.replace("``", "`")
    return first.replace("|", "\\|")


def _render_signature(name: str, obj) -> str:
    try:
        # eval_str resolves the stringized annotations that
        # `from __future__ import annotations` leaves behind.
        signature = str(inspect.signature(obj, eval_str=True))
    except (TypeError, ValueError, NameError):
        try:
            signature = str(inspect.signature(obj))
        except (TypeError, ValueError):
            return name
    # Annotations arrive fully qualified, which buries the type being named.
    signature = signature.replace("smartthings_local.protocol.", "")
    signature = signature.replace("smartthings_local.ocf.", "")
    signature = signature.replace("smartthings_local.", "")
    for module in ("dtls_probe.", "dtls_session.", "ocf_discovery.",
                   "ocf_multicast.", "auth.", "endpoint.", "errors."):
        signature = signature.replace(module, "")
    for suffix in (" -> None", " -> 'None'"):
        if inspect.isclass(obj) and signature.endswith(suffix):
            signature = signature[: -len(suffix)]
    # A method is read as a name and a call shape, so the receiver is noise.
    signature = signature.replace("(self, ", "(").replace("(self)", "()")
    return f"{name}{signature}"


def _kind(obj) -> str:
    if inspect.isclass(obj):
        return "exception" if issubclass(obj, BaseException) else "class"
    if inspect.isfunction(obj) or inspect.isbuiltin(obj):
        return "function"
    return type(obj).__name__


def _render_member(name: str, obj) -> list[str]:
    kind = _kind(obj)
    lines = []
    if kind in ("class", "exception", "function"):
        lines.append(f"#### `{_render_signature(name, obj)}`")
    else:
        lines.append(f"#### `{name}`")
    summary = _summary(obj)
    detail = f"*{kind}*"
    if kind not in ("class", "exception", "function"):
        # A constant's value is the useful part, and its docstring is its
        # type's. Only render plain data, and keep it short.
        if isinstance(obj, (str, bytes, int, float, bool)) or (
            isinstance(obj, tuple)
            and all(isinstance(item, (str, bytes, int, float, bool))
                    for item in obj)
        ):
            rendered = repr(obj)
            if len(rendered) <= 120:
                detail += f" — `{rendered}`"
    elif summary:
        detail += f" — {summary}"
    lines.append("")
    lines.append(detail)
    if kind in ("class", "exception"):
        methods = [
            (member_name, member)
            for member_name, member in vars(obj).items()
            if not member_name.startswith("_")
            and (inspect.isfunction(member) or isinstance(member, (classmethod, staticmethod)))
        ]
        if methods:
            lines.append("")
            for member_name, member in sorted(methods):
                underlying = getattr(member, "__func__", member)
                rendered = _render_signature(member_name, underlying)
                member_summary = _summary(underlying)
                bullet = f"- `{rendered}`"
                if member_summary:
                    bullet += f" — {member_summary}"
                lines.append(bullet)
    lines.append("")
    return lines


def render() -> str:
    lines = [PREAMBLE]
    for module_name, names in SUPPORTED_DOWNSTREAM_IMPORTS.items():
        module = importlib.import_module(module_name)
        lines.append(f"## `{module_name}`")
        lines.append("")
        module_summary = _summary(module)
        if module_summary:
            lines.append(module_summary)
            lines.append("")
        for name in names:
            lines.extend(_render_member(name, getattr(module, name)))
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if docs/api.md does not match the code",
    )
    args = parser.parse_args(argv)
    rendered = render()
    if args.check:
        current = DOC_PATH.read_text() if DOC_PATH.exists() else ""
        if current != rendered:
            print(
                "docs/api.md is stale; "
                "run python tools/generate_api_docs.py",
                file=sys.stderr,
            )
            return 1
        return 0
    DOC_PATH.write_text(rendered)
    print(f"wrote {DOC_PATH.relative_to(DOC_PATH.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
